name: Changesets

run-name: ${{ github.actor }} is learning Github Actions

on:
    push:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    version:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: 코드 레포를 체크아웃한다
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: nodejs를 설치한다
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: PNPM을 설치한다
              run: npm i pnpm@latest -g
            - name: .npmrc를 생성한다
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
            - name: PNPM config를 설정한다
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
            - name: dependencies를 설치한다
              run: pnpm install
            - name: 버전을 생성한다
              run: pnpm ci:version
            - name: 버저닝된 패키지를 배포한다
              run: pnpm ci:publish
