name: Changesets

run-name: ${{ github.actor }} is learning Github Actions

on:
    push:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    version:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: 코드 레포를 체크아웃한다
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: nodejs를 설치한다
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: PNPM을 설치한다
              run: npm i pnpm@latest -g
            - name: Install dependencies
              run: pnpm install
            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  version: pnpm ci:version
                  publish: pnpm ci:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
